
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grafos.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 850)  # Aumentamos el tamaño para acomodar más widgets
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Tabla de entrada de la matriz de pesos
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 50, 421, 151))
        self.tableWidget.setRowCount(4)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")

        # Botón para dibujar grafo
        self.btnPintarGrafo = QtWidgets.QPushButton(self.centralwidget)
        self.btnPintarGrafo.setGeometry(QtCore.QRect(190, 210, 141, 31))
        self.btnPintarGrafo.setObjectName("btnPintarGrafo")

        # Botón para generar la matriz de adyacencia
        self.btnGenerarMatriz = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerarMatriz.setGeometry(QtCore.QRect(800, 50, 141, 31))
        self.btnGenerarMatriz.setObjectName("btnGenerarMatriz")

        # Botones para calcular trayectorias k=2 y k=3
        self.btnK2Trayectorias = QtWidgets.QPushButton(self.centralwidget)
        self.btnK2Trayectorias.setGeometry(QtCore.QRect(400, 210, 141, 31))
        self.btnK2Trayectorias.setObjectName("btnK2Trayectorias")

        self.btnK3Trayectorias = QtWidgets.QPushButton(self.centralwidget)
        self.btnK3Trayectorias.setGeometry(QtCore.QRect(610, 210, 141, 31))
        self.btnK3Trayectorias.setObjectName("btnK3Trayectorias")

        # Tabla para trayectorias k=2
        self.tableWidgetK2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetK2.setGeometry(QtCore.QRect(50, 300, 421, 151))
        self.tableWidgetK2.setRowCount(4)
        self.tableWidgetK2.setColumnCount(4)
        self.tableWidgetK2.setObjectName("tableWidgetK2")

        # Tabla para trayectorias k=3
        self.tableWidgetK3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetK3.setGeometry(QtCore.QRect(50, 500, 421, 151))
        self.tableWidgetK3.setRowCount(4)
        self.tableWidgetK3.setColumnCount(4)
        self.tableWidgetK3.setObjectName("tableWidgetK3")

        # Área para grafo
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(500, 300, 651, 451))
        self.graphicsView.setObjectName("graphicsView")

        # Etiquetas
        self.lblTtitulo = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo.setGeometry(QtCore.QRect(300, 10, 601, 31))
        self.lblTtitulo.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
                                      "color:rgb(0, 85, 255);")
        self.lblTtitulo.setObjectName("lblTtitulo")

        self.lblTtitulo_3 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_3.setGeometry(QtCore.QRect(50, 10, 161, 31))
        self.lblTtitulo_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
                                        "color:rgb(0, 85, 255);")
        self.lblTtitulo_3.setObjectName("lblTtitulo_3")

        self.lblTrayectoriasK2 = QtWidgets.QLabel(self.centralwidget)
        self.lblTrayectoriasK2.setGeometry(QtCore.QRect(50, 270, 221, 31))
        self.lblTrayectoriasK2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
                                             "color:rgb(0, 85, 255);")
        self.lblTrayectoriasK2.setObjectName("lblTrayectoriasK2")

        self.lblTrayectoriasK3 = QtWidgets.QLabel(self.centralwidget)
        self.lblTrayectoriasK3.setGeometry(QtCore.QRect(50, 470, 221, 31))
        self.lblTrayectoriasK3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
                                             "color:rgb(0, 85, 255);")
        self.lblTrayectoriasK3.setObjectName("lblTrayectoriasK3")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setToolTip(_translate("MainWindow", "Ingrese los valores de la matriz de adyacencia"))
        self.btnPintarGrafo.setText(_translate("MainWindow", "Dibujar Grafo"))
        self.btnGenerarMatriz.setText(_translate("MainWindow", "Generar Matriz"))
        self.btnK2Trayectorias.setText(_translate("MainWindow", "Calcular K=2"))
        self.btnK3Trayectorias.setText(_translate("MainWindow", "Calcular K=3"))
        self.lblTtitulo.setText(_translate("MainWindow", "Grafos por Thomas Osorio Zambrano"))
        self.lblTtitulo_3.setText(_translate("MainWindow", "Matriz de Pesos>>"))
        self.lblTrayectoriasK2.setText(_translate("MainWindow", "Trayectorias K=2:"))
        self.lblTrayectoriasK3.setText(_translate("MainWindow", "Trayectorias K=3:"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
